repo: src
patches:
-
  owners: null
  file: 005-Add-support-for-using-seccomp_bpf-on-mips64el.patch
  descripion: null
-
  owners: null
  file: 006-Set-kernal-page-size-to-16K-on-loongson-MIPS-archtec.patch
  descripion: null
-
  owners: null
  file: 007-Add-mips64el-redhat-linux-to-gcc_toolchain-for-mips6.patch
  descripion: null
-
  owners: null
  file: 009-Fix-mips-cross-toolchain-build-src-crypto-ec-p256-64.patch
  descripion: null
-
  owners: null
  file: 010-Fix-error-about-relocation-truncated-to-fit-R_MIPS_C.patch
  descripion: null
-
  owners: zcbenz
  file: 011-backport-sqlite-8a87f7e.patch
  descripion: null
-
  owners: zcbenz
  file: 012-backport-sqlite-9851f2e.patch
  descripion: null
-
  owners: zcbenz
  file: 013-backport-sqlite-3d8ec48.patch
  descripion: null
-
  owners: zcbenz
  file: 014-support-old-nss.patch
  descripion: null
