repo: src
patches:
-
  owners: alespergl
  file: 001-build_gn.patch
  descripion: null
-
  owners: alespergl, deepak1556
  file: 002-dcheck.patch
  descripion: |
    This disables some debug checks which currently fail when running the Electron
    test suite. In general there should be sustained effort to have all debug checks
    enabled. If you want to help, choose one of the diffs below and remove it. Then
    build Electron (debug configuration) and make sure all tests pass on the CI
    systems. Unfortunately the tests don't always cover the check failures, so it's
    good to also run some non-trivial Electron app to verify.
    
    Apart from getting rid of a whole diff, you may also be able to replace one diff
    with another which enables at least some of the previously disabled checks. For
    example, the checks might be disabled for a whole build target, but actually
    only one or two specific checks fail. Then it's better to simply comment out the
    failing checks and allow the rest of the target to have them enabled.
    
    Please keep the following lists updated.
    
    The ELECTRON_NO_DCHECK build flag disables debug checks universally.
    This patch applies the flag to the following GN targets:
    
      third_party/WebKit/Source/core/loader:loader
      url:url
    
    These files have debug checks explicitly commented out:
    
      base/memory/weak_ptr.cc
      base/process/kill_win.cc
      components/viz/service/display/program_binding.h
      content/browser/frame_host/navigation_controller_impl.cc
      content/browser/frame_host/render_frame_host_impl.cc
      content/browser/renderer_host/render_widget_host_view_mac.mm
      ppapi/host/ppapi_host.cc
      third_party/WebKit/Source/core/dom/Node.cpp
      third_party/WebKit/Source/platform/wtf/text/StringImpl.h
      ui/base/clipboard/clipboard_win.cc
-
  owners: zcbenz
  file: 003-accelerator.patch
  descripion: null
-
  owners: alespergl
  file: 004-allow_new_privs.patch
  descripion: null
-
  owners: null
  file: 005-app_indicator_icon_menu.patch
  descripion: null
-
  owners: zcbenz
  file: 006-blink_file_path.patch
  descripion: null
-
  owners: zcbenz
  file: 007-blink_local_frame.patch
  descripion: |
    According to electron/electron#3699, it is unreliable to use |unload|
    event for process.exit('exit'), so we have to do that in
    willReleaseScriptContext.
    
    However Chromium then disallowed scripting in willReleaseScriptContext
    in https://codereview.chromium.org/1657583002, and crash will happen
    when there is code doing that.
    
    This patch reverts the change to fix the crash in Electron.
-
  owners: null
  file: 008-blink_world_context.patch
  descripion: null
-
  owners: zcbenz
  file: 009-browser_compositor_mac.patch
  descripion: null
-
  owners: null
  file: 010-browser_plugin_wheel.patch
  descripion: null
-
  owners: null
  file: 011-build_toolchain_win_patch.patch
  descripion: |
    Patch the Windows build toolchain to generate unique PDB names

    When the PDB files generated by the `static_library` build are
    packaged for distribution they are all copied to a single folder,
    some of the PDB files have identical names so they end up
    overwriting each other. The missing PDB files cause linker warnings
    when building Electron in Release mode, and make it more difficult
    to debug release builds.

    This patch modifies the PDB naming convention for the
    `static_library` build configuration to ensure PDB names are unique.
    For example, instead of generating `obj/ui/base/base_cc.pdb` the
    build will now generate `obj/ui/base/obj_ui_base_base_cc.pdb`.
-
  owners: zcbenz
  file: 012-can_create_window.patch
  descripion: null
-
  owners: null
  file: 013-compositor_delegate.patch
  descripion: null
-
  owners: null
  file: 016-desktop_screen_win.patch
  descripion: null
-
  owners: zcbenz
  file: 017-disable_hidden.patch
  descripion: null
-
  owners: zcbenz
  file: 018-dom_storage_map.patch
  descripion: null
-
  owners: zcbenz
  file: 019-frame_host_manager.patch
  descripion: null
-
  owners: null
  file: 020-guest_view.patch
  descripion: null
-
  owners: tonyganch
  file: 021-latency_info.patch
  descripion: null
-
  owners: zcbenz
  file: 023-net_url_request_job.patch
  descripion: null
-
  owners: MarshallOfSound
  file: 024-new_site_instance.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 025-no_stack_dumping.patch
  descripion: null
-
  owners: deepak1556
  file: 026-out_of_process_instance.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 027-protobuf_build_gn.patch
  descripion: null
-
  owners: null
  file: 028-render_widget_host_view_base.patch
  descripion: null
-
  owners: zcbenz
  file: 029-render_widget_host_view_mac.patch
  descripion: null
-
  owners: deepak1556
  file: 030-resource_request_details.patch
  descripion: null
-
  owners: null
  file: 031-scoped_clipboard_writer.patch
  descripion: null
-
  owners: deepak1556
  file: 032-stream_resource_handler.patch
  descripion: null
-
  owners: null
  file: 034-thread_capabilities.patch
  descripion: |
    Chromium automatically drops all capabilities of renderer threads in
    Linux, which may cause issues in a context like Electron, where the main
    and renderer threads are supposed to keep inherited permissions over the
    system.
    
    See https://github.com/atom/electron/issues/3666
-
  owners: zcbenz
  file: 035-use_transparent_window.patch
  descripion: null
-
  owners: null
  file: 036-web_contents.patch
  descripion: null
-
  owners: miniak
  file: 037-webgl_context_attributes.patch
  descripion: null
-
  owners: null
  file: 038-webview_cross_drag.patch
  descripion: null
-
  owners: zcbenz
  file: 040-worker_context_will_destroy.patch
  descripion: null
-
  owners: null
  file: 042-webui_in_subframes.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 045-export_blink_webdisplayitemlist.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 046-statically_build_power_save_blocker.patch
  descripion: null
-
  owners: gavignus
  file: 047-browser_plugin_guest.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 048-disable_user_gesture_requirement_for_beforeunload_dialogs.patch
  descripion: See https://github.com/electron/electron/issues/10754
-
  owners: alexeykuzmin
  file: 049-restore_adding_custom_cors_enabled_schemes.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 052-fix_blink_property_tree_state_to_tree_string_usage.patch
  descripion: Should probably be removed since we already have DCHECKs enabled.
-
  owners: deepak1556
  file: 052-latency_histogram_macros.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 063-backport_140d82d6f8e2.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 064-backport_4dfcf263240a.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 065-backport_81e7f1791035.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 066-backport_99b48b47f11f.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 067-backport_1ed08ea9dbb0.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 068-backport_97f5f9df6988.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 071-add_atomic_lib_to_dependencies_even_for_sysroot_builds.patch
  descripion: null
-
  owners: zcbenz
  file: 073-gin_enable_disable_v8_platform.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 074-backport_015a8b82b8e1.patch
  descripion: null
-
  owners: deepak1556
  file: 074-disable-recursive-surface-sync.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 075-backport_a6977980088b.patch
  descripion: null
-
  owners: null
  file: 075-can_disable_desktop_capture_throttling.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 076-backport_72f0a9302524.patch
  descripion: null
-
  owners: codebytere
  file: 076_patch_catalog_vuln.patch
  descripion: |
    Several services require "app" capability from all other services
    (wildcard), which is in itself probably a Bad Thing; but it's
    especially bad now because the catalog service exposes module
    directory access through its app capability.
    
    This changes the catalog manifest to move the capability to a
    different more specific capability, and updates two of its
    consumers.
-
  owners: alexeykuzmin
  file: 077-backport_22c1deb1bcd1.patch
  descripion: null
-
  owners: null
  file: 077-fix-touchpad-lagging-issue.patch
  descripion: |
    Fixes the touchpad lagging issue: https://crbug.com/713907, https://crbug.com/793036.
    Backported from https://crrev.com/c/867070.
-
  owners: alexeykuzmin
  file: 078-backport_ea2ad20b708c.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 079-backport_d3131378a4ef.patch
  descripion: null
-
  owners: alexeykuzmin
  file: 080-backport_1d39d46571bb.patch
  descripion: null
-
  owners: deepak1556
  file: 081-blink-worker-enable-csp-in-file-scheme.patch
  descripion: null
-
  owners: zcbenz
  file: 082-fix-arm64-linking-error.patch
  descripion: Do not use system freetype for arm64
