version: 1.0.{build}
build_cloud: libcc-20
image: libcc-20core
clone_folder: d:\build
environment:
  matrix:
  - TARGET_ARCH: ia32
    COMPONENT: shared_library
  - TARGET_ARCH: x64
    COMPONENT: shared_library
  - TARGET_ARCH: ia32
    COMPONENT: static_library
  - TARGET_ARCH: x64
    COMPONENT: static_library
build_script:
- ps: >-
    if(($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME -split "/")[0] -eq ($env:APPVEYOR_REPO_NAME -split "/")[0]) {
      Write-warning "Skipping PR build for branch"; Exit-AppveyorBuild
    } else {
      script\cibuild.ps1

      if ($? -ne 'True') {
        throw "Build failed with exit code $?"
      } else {
        "Build succeeded."
      }
    }
test_script:
- ps: >-
    if ($env:COMPONENT -eq 'shared_library') {
      $env:DISABLE_CRASH_REPORTER_TESTS = 'true'
      $env:LIBCHROMIUMCONTENT_COMMIT = $env:APPVEYOR_REPO_COMMIT
      git clone --depth 1 https://github.com/electron/electron.git
      cd electron
      Write-Output "Bootstrapping for commit $env:LIBCHROMIUMCONTENT_COMMIT"
      python script\bootstrap.py -v --dev --libcc_source_path d:\build\dist\main\src --libcc_shared_library_path d:\build\dist\main\shared_library --libcc_static_library_path d:\build\dist\main\static_library
      python script\build.py -c D
      python script\test.py --ci
    }
artifacts:
- path: libchromiumcontent.zip
  name: libchromiumcontent.zip
- path: libchromiumcontent-static.zip
  name: libchromiumcontent-static.zip
deploy: off
