repo: src/v8
patches:
-
  owners: alespergl
  file: build_gn.patch
  description: null
-
  owners: zcbenz
  file: array_buffer.patch
  description: null
-
  owners: zcbenz
  file: ostreams.patch
  description: null
-
  owners: alexeykuzmin,alespergl
  file: export_platform.patch
  description: |
    v8::Platform::SystemClockTimeMillis must be exported so that node::NodePlatform can call it
-
  owners: alespergl
  file: dcheck.patch
  description: null
-
  owners: nitsakh
  file: disable-warning-win.patch
  description:
    Disable unit test windows build warning
-
  owners: alexeykuzmin
  file: backport_39d546a.patch
  description: Node 10.0.0 needs it.
-
  owners: alexeykuzmin
  file: backport_ff0a97933.patch
  description: Node 10.2.0 needs it.
-
  owners: alexeykuzmin
  file: backport_9fb02b526.patch
  description: Node 10.2.0 needs it.
-
  owners: alexeykuzmin
  file: backport_23652c5f.patch
  description: Node 10.2.0 needs it.
-
  owners: codebytere
  file: backport_91ddb65d.patch
  description: Node 10.6.0 needs it.
-
  owners: codebytere
  file: cherry-pick_6989b3f6d7.patch
  description: Node 10.6.0 needs it.
-
  owners: codebytere
  file: cherry-pick_a440efb27f.patch
  description: Node 10.6.0 needs it.
-
  owners: codebytere
  file: cherry-pick_5dd3395.patch
  description: Node 10.6.0 needs it.
-
  owners: codebytere
  file: backport_aa6ce3e.patch
  description: Node 10.6.0 needs it.
-
  owners: codebytere
  file: cherry-pick_b20faff.patch
  description: Node 10.6.0 needs it.
-
  owners: codebytere
  file: cherry-pick_acc336c.patch
  description: Node 10.6.0 needs it.
-
  owners: codebytere
  file: cherry-pick_70c4340.patch
  description: Node 10.6.0 needs it.
