repo: src/v8
patches:
-
  owners: alespergl
  file: build_gn.patch
  descripion: null
-
  owners: zcbenz
  file: array_buffer.patch
  descripion: null
-
  owners: zcbenz
  file: mksnapshot.patch
  descripion: null
-
  owners: zcbenz
  file: ostreams.patch
  descripion: null
-
  owners: alexeykuzmin
  file: export_platform.patch
  descripion: null
-
  owners: codebytere
  file: cherry_pick_37a3a15c3.patch
  descripion: null
-
  owners: alespergl
  file: backport_3ecb047.patch
  descripion: |
    Fixes security bug
    https://bugs.chromium.org/p/project-zero/issues/detail?id=1445
-
  owners: alespergl
  file: backport_a2b91ed.patch
  descripion: |
    Fixes security bug
    https://bugs.chromium.org/p/project-zero/issues/detail?id=1446
-
  owners: codebytere
  file: cherry_pick_c690f54d95802.patch
  descripion: null
-
  owners: codebytere
  file: cherry_pick_98c40a4bae915.patch
  descripion: null
-
  owners: codebytere
  file: backport_14ac02c.patch
  descripion: null
-
  owners: codebytere
  file: backport_76c3ac5.patch
  descripion: null
-
  owners: codebytere
  file: cherry_pick_c3458a8.patch
  descripion: null
-
  owners: codebytere
  file: cherry_pick_50f7455.patch
  descripion: null
-
  owners: codebytere
  file: cherry_pick_ac0fe8ec.patch
  descripion: null
-
  owners: alespergl
  file: dcheck.patch
  descripion: null
