repo: src/v8
patches:
-
  author: Ales Pergl <alpergl@microsoft.com>
  file: build_gn.patch
  description: null
-
  author: Cheng Zhao <zcbenz@gmail.com>
  file: array_buffer.patch
  description: null
-
  author: Cheng Zhao <zcbenz@gmail.com>
  file: ostreams.patch
  description: null
-
  author: Aleksei Kuzmin <alkuzmin@microsoft.com>
  file: export_platform.patch
  description: |
    v8::Platform::SystemClockTimeMillis must be exported so that node::NodePlatform can call it
-
  author: Ales Pergl <alpergl@microsoft.com>
  file: dcheck.patch
  description: null
-
  author: Nitish Sakhawalkar <nitsakh@icloud.com>
  file: disable-warning-win.patch
  description:
    Disable unit test windows build warning
-
  author: Aleksei Kuzmin <alkuzmin@microsoft.com>
  file: backport_b767cde1e7.patch
  description: Node 10.0.0 needs it.
-
  author: Aleksei Kuzmin <alkuzmin@microsoft.com>
  file: backport_39d546a.patch
  description: Node 10.0.0 needs it.
-
  author: Aleksei Kuzmin <alkuzmin@microsoft.com>
  file: backport_ff0a97933.patch
  description: Node 10.2.0 needs it.
-
  author: Aleksei Kuzmin <alkuzmin@microsoft.com>
  file: backport_9fb02b526.patch
  description: Node 10.2.0 needs it.
-
  author: Aleksei Kuzmin <alkuzmin@microsoft.com>
  file: backport_23652c5f.patch
  description: Node 10.2.0 needs it.
-
  author: Aleksei Kuzmin <alkuzmin@microsoft.com>
  file: backport_b49206d.patch
  description: Node 10.2.0 needs it.
-
  author: Nitish Sakhawalkar <nitsakh@icloud.com>
  file: backport_50206308.patch
  description: |
    Part (1/2) of backporting the array splice perf regression caused in ch66
-
  author: Nitish Sakhawalkar <nitsakh@icloud.com>
  file: backport_2eb23a17.patch
  description: |
    Part (2/2) of backporting the array splice perf regression caused in ch66
