version: 2.0
jobs:
  libchromiumcontent-linux-x64:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: x64
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c static_library
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c shared_library
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip
      - store_artifacts:
          path: libchromiumcontent-static.zip

  libchromiumcontent-linux-ia32:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: ia32
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c static_library
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c shared_library
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip
      - store_artifacts:
          path: libchromiumcontent-static.zip

  libchromiumcontent-linux-arm:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c static_library
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c shared_library
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip
      - store_artifacts:
          path: libchromiumcontent-static.zip

  libchromiumcontent-linux-arm64:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm64
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c static_library
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c shared_library
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip
      - store_artifacts:
          path: libchromiumcontent-static.zip

workflows:
  version: 2
  build-x64:
    jobs:
      - libchromiumcontent-linux-x64
  build-ia32:
    jobs:
      - libchromiumcontent-linux-ia32
  build-arm:
    jobs:
      - libchromiumcontent-linux-arm
  build-arm64:
    jobs:
      - libchromiumcontent-linux-arm64
