version: 2.0
jobs:
  libchromiumcontent-linux-x64-shared:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: x64
          COMPONENT: shared_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip

  libchromiumcontent-linux-x64-static:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: x64
          COMPONENT: static_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent-static.zip

  libchromiumcontent-linux-x64-test:
    docker:
      - image: electronbuilds/electron:0.0.3
        environment:
          TARGET_ARCH: x64
          DISPLAY: ':99.0'
    resource_class: 2xlarge
    steps:
      - run:
          name: Checkout Electron for testing
          command: |
            git clone --depth 1 https://github.com/electron/electron.git
      - run:
          name: Setup for headless testing
          command: sh -e /etc/init.d/xvfb start
      - run:
         name: Bootstrap Electron
         command: |
            cd electron
            echo 'export LIBCHROMIUMCONTENT_COMMIT=$CIRCLE_SHA1' >> $BASH_ENV
            echo "Bootstrapping Electron for release build with commit $CIRCLE_SHA1"
            script/bootstrap.py --target_arch=$TARGET_ARCH
      - run:
         name: Build Electron release
         command: |
            cd electron
            script/build.py -c R
      - run:
          name: Test Electron
          environment:
            MOCHA_FILE: junit/test-results.xml
            MOCHA_REPORTER: mocha-junit-reporter
          command: |
            cd electron
            mkdir junit
            script/test.py --ci -c R
      - run:
          name: Verify FFmpeg
          command: |
             cd electron
             script/verify-ffmpeg.py
      - store_test_results:
          path: electron/junit
      - store_artifacts:
          path: electron/junit

  libchromiumcontent-linux-ia32-shared:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: ia32
          COMPONENT: shared_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip

  libchromiumcontent-linux-ia32-static:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: ia32
          COMPONENT: static_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent-static.zip

  libchromiumcontent-linux-arm-shared:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm
          COMPONENT: shared_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip

  libchromiumcontent-linux-arm-static:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm
          COMPONENT: static_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent-static.zip

  libchromiumcontent-linux-arm64-shared:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm64
          COMPONENT: shared_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip

  libchromiumcontent-linux-arm64-static:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm64
          COMPONENT: static_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent-static.zip

  libchromiumcontent-linux-mips64el-shared:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: mips64el
          COMPONENT: shared_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build shared library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent.zip

  libchromiumcontent-linux-mips64el-static:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: mips64el
          COMPONENT: static_library
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: script/bootstrap
      - run:
          name: Update
          command: script/update --clean -t $TARGET_ARCH
      - run:
          name: Build static library
          command: script/build -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Build FFmpeg
          command: script/build -t $TARGET_ARCH -c ffmpeg
      - run:
          name: Create distribution
          command: script/create-dist -t $TARGET_ARCH -c $COMPONENT
      - run:
          name: Upload to S3
          command: |
            if [[ -z "${LIBCHROMIUMCONTENT_S3_ACCESS_KEY}" ]]; then
              echo "Skipping upload to S3"
            else
              script/upload -t $TARGET_ARCH
            fi
      - store_artifacts:
          path: libchromiumcontent-static.zip

workflows:
  version: 2
  build-x64:
    jobs:
      - libchromiumcontent-linux-x64-shared
      - libchromiumcontent-linux-x64-static
      - libchromiumcontent-linux-x64-test:
          requires:
            - libchromiumcontent-linux-x64-shared
            - libchromiumcontent-linux-x64-static
  build-ia32:
    jobs:
      - libchromiumcontent-linux-ia32-shared
      - libchromiumcontent-linux-ia32-static
  build-arm:
    jobs:
      - libchromiumcontent-linux-arm-shared
      - libchromiumcontent-linux-arm-static
  build-arm64:
    jobs:
      - libchromiumcontent-linux-arm64-shared
      - libchromiumcontent-linux-arm64-static
