version: 2.0
jobs:
  libchromiumcontent-linux-x64-static-build:
    docker:
      - image: electronbuilds/libchromiumcontent:circleci_test0.0.1
        environment:
          TARGET_ARCH: x64
          LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: cp -r src/out-x64 /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out-x64

  libchromiumcontent-linux-x64-shared-build:
      docker:
        - image: electronbuilds/libchromiumcontent:circleci_test0.0.1
          environment:
            TARGET_ARCH: x64
            LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - run: script/update --clean -t $TARGET_ARCH
        - run: script/build -t $TARGET_ARCH -c shared_library
        - run: cp -r src/out-x64 /tmp/workspace
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - out-x64

  libchromiumcontent-linux-x64-upload:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: x64
            LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - attach_workspace:
            at: /tmp/workspace
        - run: cp -r /tmp/workspace/out-x64 src
        - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-ia32-static-build:
    docker:
      - image: electronbuilds/libchromiumcontent:circleci_test0.0.1
        environment:
          TARGET_ARCH: ia32
          LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: cp -r src/out-ia32 /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out-ia32

  libchromiumcontent-linux-ia32-shared-build:
      docker:
        - image: electronbuilds/libchromiumcontent:circleci_test0.0.1
          environment:
            TARGET_ARCH: ia32
            LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - run: script/update --clean -t $TARGET_ARCH
        - run: script/build -t $TARGET_ARCH -c shared_library
        - run: cp -r src/out-ia32 /tmp/workspace
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - out-ia32

  libchromiumcontent-linux-ia32-upload:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: ia32
            LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - attach_workspace:
            at: /tmp/workspace
        - run: cp -r /tmp/workspace/out-ia32 src
        - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-arm-static-build:
    docker:
      - image: electronbuilds/libchromiumcontent:circleci_test0.0.1
        environment:
          TARGET_ARCH: arm
          LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: cp -r src/out-arm /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out-arm

  libchromiumcontent-linux-arm-shared-build:
      docker:
        - image: electronbuilds/libchromiumcontent:circleci_test0.0.1
          environment:
            TARGET_ARCH: arm
            LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - run: script/update --clean -t $TARGET_ARCH
        - run: script/build -t $TARGET_ARCH -c shared_library
        - run: cp -r src/out-arm /tmp/workspace
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - out-arm

  libchromiumcontent-linux-arm-upload:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: arm
            LIBCHROMIUMCONTENT_GIT_CACHE: /tmp/libcc_cache
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - attach_workspace:
            at: /tmp/workspace
        - run: cp -r /tmp/workspace/out-arm src
        - run: script/upload -t $TARGET_ARCH

workflows:
  version: 2
  build:
    jobs:
      - libchromiumcontent-linux-x64-static-build
      - libchromiumcontent-linux-x64-shared-build
      - libchromiumcontent-linux-x64-upload:
          requires:
            - libchromiumcontent-linux-x64-static-build
            - libchromiumcontent-linux-x64-shared-build
      - libchromiumcontent-linux-ia32-static-build
      - libchromiumcontent-linux-ia32-shared-build
      - libchromiumcontent-linux-ia32-upload:
          requires:
            - libchromiumcontent-linux-ia32-static-build
            - libchromiumcontent-linux-ia32-shared-build
      - libchromiumcontent-linux-arm-static-build
      - libchromiumcontent-linux-arm-shared-build
      - libchromiumcontent-linux-arm-upload:
          requires:
            - libchromiumcontent-linux-arm-static-build
            - libchromiumcontent-linux-arm-shared-build
