version: 2.0
jobs:
  libchromiumcontent-linux-x64:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: x64
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c shared_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: script/create-dist -t $TARGET_ARCH
      - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-x64-static-build:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: x64
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/static_library"
      - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/ffmpeg"
      - run: cp -r "src/out-${TARGET_ARCH}/static_library" "/tmp/workspace/out-${TARGET_ARCH}"
      - run: cp -r "src/out-${TARGET_ARCH}/ffmpeg" "/tmp/workspace/out-${TARGET_ARCH}"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out-x64/static_library
            - out-x64/ffmpeg

  libchromiumcontent-linux-x64-shared-build:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: x64
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - run: script/update --clean -t $TARGET_ARCH
        - run: script/build -t $TARGET_ARCH -c shared_library
        - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/shared_library"
        - run: cp -r "src/out-${TARGET_ARCH}/shared_library" "/tmp/workspace/out-${TARGET_ARCH}"
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - out-x64/shared_library

  libchromiumcontent-linux-x64-upload:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: x64
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - attach_workspace:
            at: /home/builduser/project/src
        - run: script/create-dist -t $TARGET_ARCH
        - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-ia32:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: ia32
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c shared_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: script/create-dist -t $TARGET_ARCH
      - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-ia32-static-build:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: ia32
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/static_library"
      - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/ffmpeg"
      - run: cp -r "src/out-${TARGET_ARCH}/static_library" "/tmp/workspace/out-${TARGET_ARCH}"
      - run: cp -r "src/out-${TARGET_ARCH}/ffmpeg" "/tmp/workspace/out-${TARGET_ARCH}"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out-ia32/static_library
            - out-ia32/ffmpeg

  libchromiumcontent-linux-ia32-shared-build:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: ia32
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - run: script/update --clean -t $TARGET_ARCH
        - run: script/build -t $TARGET_ARCH -c shared_library
        - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/shared_library"
        - run: cp -r "src/out-${TARGET_ARCH}/shared_library" "/tmp/workspace/out-${TARGET_ARCH}"
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - out-ia32/shared_library

  libchromiumcontent-linux-ia32-upload:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: ia32
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - attach_workspace:
            at: /home/builduser/project/src
        - run: script/create-dist -t $TARGET_ARCH
        - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-arm:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c shared_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: script/create-dist -t $TARGET_ARCH
      - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-arm-static-build:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/static_library"
      - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/ffmpeg"
      - run: cp -r "src/out-${TARGET_ARCH}/static_library" "/tmp/workspace/out-${TARGET_ARCH}"
      - run: cp -r "src/out-${TARGET_ARCH}/ffmpeg" "/tmp/workspace/out-${TARGET_ARCH}"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - out-arm/static_library
            - out-arm/ffmpeg

  libchromiumcontent-linux-arm-shared-build:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: arm
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - run: script/update --clean -t $TARGET_ARCH
        - run: script/build -t $TARGET_ARCH -c shared_library
        - run: mkdir -p "/tmp/workspace/out-${TARGET_ARCH}/shared_library"
        - run: cp -r "src/out-${TARGET_ARCH}/shared_library" "/tmp/workspace/out-${TARGET_ARCH}"
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - out-arm/shared_library

  libchromiumcontent-linux-arm-upload:
      docker:
        - image: electronbuilds/libchromiumcontent:0.0.4
          environment:
            TARGET_ARCH: arm
      resource_class: xlarge
      steps:
        - checkout
        - run: script/bootstrap
        - attach_workspace:
            at: /home/builduser/project/src
        - run: script/create-dist -t $TARGET_ARCH
        - run: script/upload -t $TARGET_ARCH

  libchromiumcontent-linux-arm64:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.4
        environment:
          TARGET_ARCH: arm64
    resource_class: xlarge
    steps:
      - checkout
      - run: script/bootstrap
      - run: script/update --clean -t $TARGET_ARCH
      - run: script/build -t $TARGET_ARCH -c static_library
      - run: script/build -t $TARGET_ARCH -c shared_library
      - run: script/build -t $TARGET_ARCH -c ffmpeg
      - run: script/create-dist -t $TARGET_ARCH
      - run: script/upload -t $TARGET_ARCH

workflows:
  version: 2
  build-x64:
    jobs:
      - libchromiumcontent-linux-x64
  build-ia32:
    jobs:
      - libchromiumcontent-linux-ia32
  build-arm:
    jobs:
      - libchromiumcontent-linux-arm
  build-arm64:
    jobs:
      - libchromiumcontent-linux-arm64
