version: 2.0
jobs:
  sync-src:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.3
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - chromium-src-{{ checksum "VERSION" }}
          # fallback to using the latest cache if no exact match is found
          - chromium-src-
      - run: script/bootstrap
      - run: script/update --clean --source_only
      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - '*'
            - '**/*'
      - save_cache:
          paths:
            - src
          key: chromium-src-{{ checksum "VERSION" }}
  libchromiumcontent-linux-x64:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.3
        environment:
          TARGET_ARCH: x64
    resource_class: xlarge
    steps:
      - run: mkdir /tmp/workspace
      # grab source from workspace
      - attach_workspace:
          at: /tmp/workspace
      - run: cp -r /tmp/workspace/* .
      - run: update -t ${TARGET_ARCH}
      - run: update build -t ${TARGET_ARCH}
      - run: create-dist -t ${TARGET_ARCH}
      - run: upload -t ${TARGET_ARCH}

  libchromiumcontent-linux-ia32:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.3
        environment:
          TARGET_ARCH: ia32
    resource_class: xlarge
    steps:
      - run: mkdir /tmp/workspace
      # grab source from workspace
      - attach_workspace:
          at: /tmp/workspace
      - run: cp -r /tmp/workspace/* .
      - run: update -t ${TARGET_ARCH}
      - run: update build -t ${TARGET_ARCH}
      - run: create-dist -t ${TARGET_ARCH}
      - run: upload -t ${TARGET_ARCH}

  libchromiumcontent-linux-arm:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.3
        environment:
          TARGET_ARCH: arm
    resource_class: xlarge
    steps:
      - run: mkdir /tmp/workspace
      # grab source from workspace
      - attach_workspace:
          at: /tmp/workspace
      - run: cp -r /tmp/workspace/* .
      - run: update -t ${TARGET_ARCH}
      - run: update build -t ${TARGET_ARCH}
      - run: create-dist -t ${TARGET_ARCH}
      - run: upload -t ${TARGET_ARCH}

workflows:
  version: 2
  build:
    jobs:
      - sync-src
      - libchromiumcontent-linux-x64:
           requires:
             - sync-src
      - libchromiumcontent-linux-ia32:
           requires:
             - sync-src
      - libchromiumcontent-linux-arm:
           requires:
             - sync-src
