version: 2.0
jobs:
  build:
    docker:
      - image: electronbuilds/libchromiumcontent:0.0.1
    resource_class: xlarge
    steps:
       - run: set +e && ssh -T -oStrictHostKeyChecking=no git@github.com && set -e
       - checkout
       - run: script/cibuild
