repo: src/third_party/crashpad/crashpad
patches:
-
  owners: nornagon
  file: http_status.patch
  description: |
    Accept all HTTP codes in [200, 300) as successful, instead of just 200.
    For example HockeyApp responds with 202.
